# Generated by Django 5.0.7 on 2024-07-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adresse',
            field=models.CharField(default='ministère d`Agriculture', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
