# Generated by Django 5.0.7 on 2024-08-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sharekey',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
