# Generated by Django 5.0.7 on 2024-08-07 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_file_sharekey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='sharekey',
            new_name='share_key',
        ),
    ]
